"""empty message

Revision ID: 712053255fc4
Revises: 
Create Date: 2017-01-05 06:44:49.119618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712053255fc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('status', sa.SmallInteger(), server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'status')
    # ### end Alembic commands ###
